name: Build Homebrew Tarball
on:
  pull_request:
    branches:
      - main
  schedule:
    - cron: "0 1 * * SUN"
  push:
    branches:
      - main
    paths-ignore:
      - "**/README.md"
  workflow_dispatch:

env:
  IMAGE_NAME: "${{ github.event.repository.name }}"

jobs:
  build:
    name: Build and upload artifact
    permissions:
      contents: read
    timeout-minutes: 60
    strategy:
      fail-fast: true
      matrix:
        platform: ["amd64", "arm64"]
    runs-on: ${{ matrix.platform == 'amd64' && 'ubuntu-24.04' || 'ubuntu-24.04-arm' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build tarball
        run: |
          podman build -t "brew-builder" --target builder -f ./Containerfile .
          podman run --name brew-extract brew-builder true
          podman cp brew-extract:/out/homebrew.tar.zst ./homebrew-${{ matrix.platform }}.tar.zst
          podman rm brew-extract

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.IMAGE_NAME }}-${{ matrix.platform }}
          path: homebrew-${{ matrix.platform }}.tar.zst
          if-no-files-found: error
          retention-days: 90
